R = [
("(previs pass 4, 5 October 2026: animation's three clips in place of the log)",
 "(previs pass 5, 5 October 2026: the camp made for its close-ups)"),
("- **The set.** Lowford's camp: the fire at (-10.5, 90.5); the log north to south at x ≈ -8.4, z 89.2 to 92.6; the bedroll south-west of the fire.",
 "- **The set.** Lowford's camp (`src/World/Camp.cs`, `Campfire.cs`): the fire at (-10.5, 90.5), burnt down to a bed of coals and four sticks in a ring of eleven field stones, sooted on their inner faces; no tripod or pot. Two sawn pine logs, barked, their ends greyed and checked: the seat north to south at x ≈ -8.5, z 89.2 to 91.4, and a lower one north of the fire. The bedroll is west of the fire."),
("- **The line of action** runs north to south through her and the fire. Every camera stays on its south side until shot 12, whose crane crosses it on purpose as she turns to fight. Shots 3 and 5 shoot across the ring's edge from the north-west, and shot 6 across the embers from the south-west: she faces the fire, so her face is only to be had from the fire's side. She is lying or kneeling and looking down, so no eyeline is crossed.",
 "- **The line of action** is her look at the fire, east to west. Her face is only to be had from the fire's side, so the cameras that hold it look back at her across the coals: shot 3 from the north-west while she lies; then 5, 6 and 6a from the west and south, the side the scene keeps to until shot 12's crane swings round behind her on purpose as she turns to fight. The cut from 3 to 5 crosses through the coals themselves, on her first movement. She is lying or kneeling and looking down, so no eyeline is crossed."),
("  - the fire drops to embers (flames 0.12; light 0 at 0.34, `#ff7430`, slow flicker);",
 "  - the fire burns down to its coals (no flames; light 0 at 0.24, `#ff7430`, slow flicker, sunk to just over the coals, so what is held over them is lit from below);"),
("- **Picture:** the embers under the tripod, and her curled on her side",
 "- **Picture:** the coals in their ring of stones, and her curled on her side"),
("### 5 · MS · 4.5 s (40 mm)\n- **Camera:** low (0.45 m) on the fire's far side at (-11.6, 0.45, 88.7), looking back across the embers at her.",
 "### 5 · MS · 4.5 s (45 mm)\n- **Camera:** low (0.5 m) on the fire's far (west) side at (-11.6, 0.5, 91.05), looking back across the coals at her, on her chest raised 0.1 m; focus on her head at f/2.4. The coals light her from below; the seat log and the frost are behind her."),
("### 6 · MS · 7.0 s (40 mm)\n- **Camera:** front three-quarter from her left, across the embers, at (-11.1, 0.85, 91.6), tracking her chest as she comes up.",
 "### 6 · MS · 7.0 s (35 mm)\n- **Camera:** front three-quarter from her left, across the coals, at (-11.1, 0.85, 91.6), tracking a point 0.22 m over her chest as she comes up, so her face and her hands are both in."),
("- **Camera:** low from the south at (-9.95, 0.75, 91.35), across the ring's stones to the coals.",
 "- **Camera:** from the south at (-9.95, 0.75, 91.35), down across the ring's stones to the coals, focus on the hand (f/2). The coals glow from inside; the light is under the hand, its back in shadow."),
("and her small on the log by the embers.", "and her small by the coals, kneeling."),
("The tripod's legs cut across shots 5 and 6; the set wants a lower tripod or a hook on a stake.",
 "(The tripod that cut across shots 5 and 6 is gone; the camp is made.)"),
("- **Shot 6** is shot from her left, across the embers, to keep the line.",
 "- **Shot 6** is shot from her left, across the embers, to keep the line.\n- **The camp is made for its close-ups.** The web game's camp was blocked out in primitives (octagonal logs, a tripod of sticks over a black ball, a ring of low-poly stones); a tripod leg and a stone lay across her in shots 5 and 6. The logs are now sawn pine, the ring made stones, the fire a bed of coals, and the tripod is gone: one traveller's fire."),
]
