PAIRS = [
("""        /* ------------------------------------- what rules a people, at the half hour -- */""",
'''        /* ------------------------------------------- the night's other kinds --
         * The owner: "variety of minion types elites and mini bosses instead of all just the
         * same models of wolves". Each people's kinds and minibosses below are on the rigs we
         * have, told apart by size, colour and above all by what they do; each has a model
         * brief for the art pass (docs/SKILLS_DESIGN.md, "Encounters"). A miniboss opens a
         * stretch of the night and wears its verb first; its kinds join the horde after it
         * (Play/Zones/Escalation.cs). */

        // The Pack.
        new() { Id = "wolf_runner", Name = "Ridge-Runner", Family = Family.Wolf, Faction = Faction.Pack, Visual = "wolf", Scale = 0.88, Tint = (1.18, 1.1, 0.92),
            Health = 26, Speed = 5.6, Damage = 8, Radius = 0.45, Xp = 4, Resists = Beast, Behavior = Behavior.Orbit, AttackEvery = 0.9,
            Lunge = new(7, 5, 0.7, 0.35, 16), Tags = [Tag.Nature], Loot = "wolf",
            Note = "A yearling, pale along the back. The young run the ring while the old ones close, and cut in when you turn to the old ones." },
        new() { Id = "boar_slurry", Name = "Slurry Sow", Family = Family.Boar, Faction = Faction.Wild, Visual = "boar", Scale = 1.22, Tint = (0.72, 0.95, 0.55), Glow = 0.06,
            Health = 70, Speed = 2.6, Damage = 12, Radius = 0.68, Mass = 3, Xp = 7, Resists = Beast, Behavior = Behavior.Chase,
            Trail = new(0.6, 1.2, 3, 0.25, School.Nature), Loot = "boar",
            Note = "She drank at the Dig's outflow and carries it with her. Where she walks the ground goes green and bites." },
        new() { Id = "wolf_howler", Name = "Old Howler", Family = Family.Wolf, Faction = Faction.Pack, Visual = "wolf", Scale = 1.1, Tint = (0.72, 0.76, 0.9),
            Health = 60, Speed = 4.0, Damage = 8, Radius = 0.55, Xp = 9, Resists = Beast, Behavior = Behavior.Ranged,
            Aura = new(8, 9, 4, Haste: 1.25, Word: "Howl"), Tags = [Tag.Nature], Loot = "wolf",
            Note = "The pack's caller. It hangs back and gives tongue, and the others run faster for it. Kill it and the hunt loses its voice." },
        new() { Id = "mb_old_tusk", Name = "Old Tusk", Family = Family.Boar, Faction = Faction.Wild, Visual = "boar", Scale = 1.9, Tint = (0.82, 0.76, 0.7),
            Health = 560, Speed = 3.3, Damage = 16, Radius = 1.0, Mass = 8, Xp = 40, Gold = 10, Resists = Beast, Behavior = Behavior.Charger,
            Charge = new(11, 5.5, 1.0, 1.0, 14), Chain = 2, Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.1,
            Lesson = "It runs its lane three times over. Put a tree in its way.",
            Note = "The oldest tusker in the Verge, scarred to the snout. It does not stop at one run, and it does not stop for you." },
        new() { Id = "mb_whitethroat", Name = "Whitethroat", Family = Family.Wolf, Faction = Faction.Pack, Visual = "wolf", Scale = 1.5, Tint = (1.25, 1.18, 1.0), Glow = 0.05,
            Health = 480, Speed = 5.8, Damage = 14, Radius = 0.8, Mass = 5, Xp = 40, Resists = Beast, Behavior = Behavior.Orbit, AttackEvery = 0.85,
            Lunge = new(8, 4, 0.65, 0.4, 18), Summon = new(14, 4, "wolf_runner", 1.2, SpawnStyle.Walk, 7, Word: "Yip! Yip!"),
            Elite = true, Miniboss = true, Loot = "miniboss", Tags = [Tag.Nature],
            Lesson = "The young run a ring round you, then cut in. Break the ring.",
            Note = "A pale she-wolf who leads the yearlings. She circles, and they circle with her, and when she cuts in so do they." },
        new() { Id = "mb_blight_mother", Name = "The Blight-Mother", Family = Family.Wolf, Faction = Faction.Pack, Visual = "wolf_blighted", Scale = 1.75, Tint = (0.75, 1.05, 0.6), Glow = 0.12,
            Health = 600, Speed = 4.0, Damage = 14, Radius = 0.95, Mass = 6, Xp = 40, Resists = new(Beast) { [School.Shadow] = 0.3 }, Behavior = Behavior.Chase,
            Trail = new(0.5, 1.4, 3.5, 0.3, School.Nature), Burst = new(3.2, 1.2, 0.9, School.Nature, StatusKind.Poison), Split = new("wolf_blighted", 3), Bite = StatusKind.Poison,
            Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.0,
            Lesson = "Sick to bursting, and so are hers. Do not be beside them when they die.",
            Note = "Swollen with the slurry and the litter it put in her. Everything about her is green, and everything she leaves is worse." },
        new() { Id = "mb_outflow_sow", Name = "The Outflow Sow", Family = Family.Boar, Faction = Faction.Wild, Visual = "boar", Scale = 2.0, Tint = (0.62, 0.88, 0.45), Glow = 0.1,
            Health = 700, Speed = 2.8, Damage = 15, Radius = 1.05, Mass = 9, Xp = 40, Gold = 10, Resists = Beast, Behavior = Behavior.Charger,
            Charge = new(10, 6, 1.1, 1.1, 12), Trail = new(0.35, 1.5, 4, 0.3, School.Nature), Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.2,
            Lesson = "Where it runs, the ground goes bad. Off the lane, and not into the slurry.",
            Note = "The sow that lives in the Dig's outflow and has grown to its size. Its lanes stay green long after it has gone down them." },
        new() { Id = "mb_caller", Name = "The Caller", Family = Family.Wolf, Faction = Faction.Pack, Visual = "wolf_alpha", Scale = 1.35, Tint = (0.68, 0.72, 0.9),
            Health = 520, Speed = 4.4, Damage = 12, Radius = 0.8, Mass = 5, Xp = 40, Resists = Beast, Behavior = Behavior.Ranged,
            Aura = new(7, 11, 4.5, Haste: 1.35, Word: "Howl"), Summon = new(12, 5, "wolf", 1.4, SpawnStyle.Walk, 9, AtTarget: true, Max: 20, Word: "Awoooo"),
            Elite = true, Miniboss = true, Loot = "miniboss", Tags = [Tag.Nature],
            Lesson = "While it howls the Pack runs faster, and more come. Find it behind them.",
            Note = "Grey-blue and old, and never at the front. It calls the Pack in from the trees and sets it running." },

        // The Risen.
        new() { Id = "bone_heap", Name = "Bone-Heap", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_minion", Scale = 1.45, Tint = (1.12, 1.06, 0.9),
            Health = 70, Speed = 2.0, Damage = 12, Radius = 0.72, Mass = 2.5, Xp = 6, Resists = Undead, Behavior = Behavior.Chase,
            Split = new("risen", 3),
            Note = "The ford's dead were buried together, and they get up together. Break it and it comes apart into three that walk on." },
        new() { Id = "drowned", Name = "Drowned", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_minion", Scale = 1.05, Tint = (0.6, 0.82, 0.88), Glow = 0.05,
            Health = 50, Speed = 2.0, Damage = 10, Radius = 0.55, Xp = 5, Resists = Undead, Behavior = Behavior.Chase,
            Trail = new(0.8, 1.3, 3.5, 0.2, School.Frost), Bite = StatusKind.Chill,
            Note = "The Low Ford keeps what it drowns. They come up weed-hung and cold, and leave the cold where they walk." },
        new() { Id = "risen_bell", Name = "Bell-Ringer", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_mage", Tint = (1.15, 0.98, 0.72),
            Health = 40, Speed = 2.2, Damage = 6, Radius = 0.5, Xp = 9, Resists = Undead, Behavior = Behavior.Ranged,
            Aura = new(9, 9, 4, Haste: 1.25, Word: "Bell"),
            Note = "The Watch rang the ford bell at dusk. One of them still does, and the dead hurry to it." },
        new() { Id = "legionary", Name = "Legion Shield-Rusher", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_warrior", Scale = 1.12, Tint = (1.05, 0.82, 0.68),
            Health = 52, Speed = 2.5, Damage = 12, Radius = 0.52, Mass = 2, Xp = 6, Resists = Undead, Behavior = Behavior.Guard,
            Guard = new(1.2, 0.6), Lunge = new(6.5, 6, 0.8, 0.4, 13),
            Note = "Older than the ford's dead, in bronze gone green. It sets its shield and comes behind it at a run. Off the line, then round the shield." },
        new() { Id = "mb_old_quarrel", Name = "Old Quarrel", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_rogue", Scale = 1.55, Tint = (1.0, 0.95, 0.85),
            Health = 380, Speed = 2.6, Damage = 10, Radius = 0.75, Mass = 4, Xp = 40, Resists = Undead, Behavior = Behavior.Ranged,
            Ranged = new() { Range = 11, Cooldown = 2.6, Speed = 12, School = School.Physical, Count = 5, Spread = 0.2, Art = "bolt_bone" },
            Elite = true, Miniboss = true, Loot = "miniboss",
            Lesson = "Five bolts in a fan. Stand in a gap, or close on it.",
            Note = "The ford's crossbowman. Dead, it shoots five where it once shot one, and it has not forgotten how to keep its distance." },
        new() { Id = "mb_decurion", Name = "The Decurion", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_warrior", Scale = 1.65, Tint = (1.05, 0.85, 0.7),
            Health = 620, Speed = 2.4, Damage = 16, Radius = 0.95, Mass = 8, Xp = 40, Resists = Undead, Behavior = Behavior.Guard,
            Guard = new(1.6, 0.75), Lunge = new(7, 6, 0.8, 0.45, 14), Summon = new(14, 4, "risen_warrior", 1.4, SpawnStyle.Rise, 3, Word: "Shields!"),
            Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.2,
            Lesson = "Shields to the front. Go round them.",
            Note = "A file-leader of the old Legion, still dressing his line. Where he stands, shields come up out of the ground beside him." },
        new() { Id = "mb_the_heap", Name = "The Heap", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_minion", Scale = 2.1, Tint = (1.15, 1.08, 0.88),
            Health = 720, Speed = 1.9, Damage = 16, Radius = 1.05, Mass = 9, Xp = 40, Resists = Undead, Behavior = Behavior.Chase,
            Split = new("bone_heap", 3), Slam = new(3.5, 6, 1.0, 2.6, 1.5, Self: true), Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.3,
            Lesson = "Many dead in one body. It comes apart, and its parts come apart.",
            Note = "A whole barrow walking. It falls on what is near it, and when it is broken it is not finished." },
        new() { Id = "mb_drowned_reeve", Name = "The Drowned Reeve", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_mage", Scale = 1.6, Tint = (0.55, 0.8, 0.9), Glow = 0.08,
            Health = 560, Speed = 2.1, Damage = 12, Radius = 0.85, Mass = 6, Xp = 40, Resists = Undead, Behavior = Behavior.Caster,
            Ranged = new() { Range = 10, Cooldown = 2.8, Speed = 7, School = School.Frost, Count = 3, Spread = 0.35, Slow = (0.6, 1.4), Art = "frost_orb" },
            Trail = new(0.6, 1.5, 4, 0.25, School.Frost), Bite = StatusKind.Chill, Elite = true, Miniboss = true, Loot = "miniboss",
            Lesson = "The ford's cold walks with it. Keep off its wet ground.",
            Note = "The reeve who kept the ford's tolls, drowned in the ford. It still walks the crossing, and the crossing walks with it." },
        new() { Id = "mb_ford_bell", Name = "The Ford Bell", Family = Family.Undead, Faction = Faction.Dead, Visual = "skeleton_mage", Scale = 1.5, Tint = (1.2, 1.0, 0.7), Glow = 0.1,
            Health = 520, Speed = 2.2, Damage = 9, Radius = 0.8, Mass = 5, Xp = 40, Resists = Undead, Behavior = Behavior.Ranged,
            Aura = new(7, 11, 4.5, Haste: 1.3, Ward: 0.25, Word: "Bell"), Raise = new(8, 3, "risen", 8), Elite = true, Miniboss = true, Loot = "miniboss",
            Lesson = "While the bell rings, the dead are quicker and harder to hurt. Silence it.",
            Note = "The ringer of the ford bell, and the bell. It rings, and the dead come quicker, and the fallen get up to come too." },

        // The Lamplings.
        new() { Id = "lampling_wick", Name = "Wick", Family = Family.Lampling, Faction = Faction.Lampling, Visual = "lampling", Scale = 0.72, Tint = (1.3, 1.12, 0.8), Glow = 0.3,
            Health = 10, Speed = 4.6, Damage = 5, Radius = 0.32, Xp = 1.5, Behavior = Behavior.Pack, AttackEvery = 0.8, Resists = new() { [School.Fire] = 0.3, [School.Frost] = -0.3 },
            Note = "The youngest of the Dig, a candle-stub on the head. Sent up first, because they run fastest and the Dig has more." },
        new() { Id = "lampling_fuse", Name = "Fuse-Runner", Family = Family.Lampling, Faction = Faction.Lampling, Visual = "lampling_sapper", Scale = 1.08, Tint = (1.3, 0.75, 0.5), Glow = 0.18,
            Health = 26, Speed = 3.2, Damage = 9, Radius = 0.42, Xp = 5, Behavior = Behavior.Charger, Resists = new() { [School.Fire] = 0.5, [School.Frost] = -0.3 },
            Charge = new(11, 5, 1.0, 0.9, 12), RunBursts = true, Burst = new(2.6, 1.6, 0.6, School.Fire, StatusKind.Burn),
            Note = "Carries a lit crate of the Boss's blasting ember at a run, straight down a lane, and goes up where the lane ends. Kill it far off." },
        new() { Id = "lampling_lamp", Name = "Lamp-Thrower", Family = Family.Lampling, Faction = Faction.Lampling, Visual = "lampling", Scale = 1.05, Tint = (0.85, 0.98, 1.35), Glow = 0.35,
            Health = 28, Speed = 2.7, Damage = 7, Radius = 0.4, Xp = 5, Behavior = Behavior.Ranged, Resists = new() { [School.Fire] = 0.5, [School.Frost] = -0.3 },
            Ranged = new() { Range = 9, Cooldown = 3.6, Speed = 9, School = School.Fire, Count = 3, Spread = 0.3, Art = "cinder" },
            Note = "Shakes three flames out of its lamp at once, in a fan. The gaps are there to be stood in." },
        new() { Id = "mb_wick_mother", Name = "The Wick-Mother", Family = Family.Lampling, Faction = Faction.Lampling, Visual = "lampling", Scale = 1.6, Tint = (1.3, 1.15, 0.8), Glow = 0.3,
            Health = 420, Speed = 3.6, Damage = 10, Radius = 0.8, Mass = 4, Xp = 40, Behavior = Behavior.Pack, Resists = new() { [School.Fire] = 0.3, [School.Frost] = -0.3 },
            Summon = new(10, 6, "lampling_wick", 1.0, SpawnStyle.Burrow, 6, AtTarget: true, Max: 30, Word: "Up, up, up!"),
            Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.0,
            Lesson = "She sends the little ones up first, all round you. They run fast and die quick.",
            Note = "Mother of every wick in her tunnel, and she has a great many tunnels. She calls; the ground answers." },
        new() { Id = "mb_bombardier", Name = "The Bombardier", Family = Family.Lampling, Faction = Faction.Lampling, Visual = "lampling_sapper", Scale = 1.6, Tint = (1.2, 0.85, 0.65),
            Health = 420, Speed = 2.7, Damage = 10, Radius = 0.8, Mass = 4, Xp = 40, Behavior = Behavior.Ranged, Resists = new() { [School.Fire] = 0.5, [School.Frost] = -0.3 },
            Ranged = new() { Range = 10, Cooldown = 3.4, Speed = 8, School = School.Fire, Lob = true, Count = 3, Spread = 0.45, Zone = new(1.8, 3.5, 0.35), Art = "firepot" },
            Burst = new(3, 1.2, 0.8, School.Fire, StatusKind.Burn), Elite = true, Miniboss = true, Loot = "miniboss",
            Lesson = "Three pots at a time. Where they land, it burns.",
            Note = "The Dig's best thrower, which is to say its worst neighbour. Three pots in the air before the first has landed." },
        new() { Id = "mb_lamplighter", Name = "The Lamplighter", Family = Family.Lampling, Faction = Faction.Lampling, Visual = "lampling", Scale = 1.7, Tint = (0.8, 0.95, 1.4), Glow = 0.45,
            Health = 480, Speed = 2.6, Damage = 9, Radius = 0.85, Mass = 5, Xp = 40, Behavior = Behavior.Ranged, Resists = new() { [School.Fire] = 0.5, [School.Frost] = -0.3 },
            Ranged = new() { Range = 10, Cooldown = 3.0, Speed = 9, School = School.Fire, Count = 5, Spread = 0.22, Art = "cinder" },
            Aura = new(8, 9, 4, Ward: 0.3, Word: "Light!"), Elite = true, Miniboss = true, Loot = "miniboss",
            Lesson = "Five flames in a fan, and its light wards the diggers near it.",
            Note = "Keeper of the Dig's great lamp, which it carries lit. The diggers in its light are harder to hurt. Put it out." },
        new() { Id = "mb_fuse_boss", Name = "The Fuse-Boss", Family = Family.Lampling, Faction = Faction.Lampling, Visual = "lampling_sapper", Scale = 1.9, Tint = (1.35, 0.7, 0.45), Glow = 0.2,
            Health = 620, Speed = 3.0, Damage = 14, Radius = 0.95, Mass = 7, Xp = 40, Behavior = Behavior.Charger, Resists = new() { [School.Fire] = 0.5, [School.Frost] = -0.3 },
            Charge = new(12, 6, 1.1, 1.0, 12), Chain = 2, Trail = new(0.3, 1.3, 3, 0.3, School.Fire), Burst = new(4, 1.6, 1.2, School.Fire, StatusKind.Burn),
            Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.2,
            Lesson = "Blasting ember carried at a run, three lanes a time. Off the lane, and away when it falls.",
            Note = "It carries the biggest crate in the Dig, and it has never once put it down. Its lanes burn behind it." },
        new() { Id = "mb_gaffer", Name = "The Gaffer", Family = Family.Lampling, Faction = Faction.Lampling, Visual = "lampling", Scale = 2.0, Tint = (0.95, 0.9, 0.8), Glow = 0.15,
            Health = 640, Speed = 3.2, Damage = 14, Radius = 1.0, Mass = 7, Xp = 40, Behavior = Behavior.Tunneler, Resists = new() { [School.Fire] = 0.3, [School.Frost] = -0.3 },
            Slam = new(3.2, 7, 1.0, 3, 1.4, Self: true), Summon = new(12, 4, "lampling", 1.2, SpawnStyle.Burrow, 5, AtTarget: true, Max: 24, Word: "Dig!"),
            Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.1,
            Lesson = "The ground is the Dig's. Where it comes up, it brings the rest.",
            Note = "A tunnel-gang's gaffer, as broad as the tunnels. It goes under, comes up beside you, and brings its gang up with it." },

        // The Kerchiefs.
        new() { Id = "levy_crossbow", Name = "Levy Crossbow", Family = Family.Kerchief, Faction = Faction.Kerchief, Visual = "kerchief_hooded", Scale = 0.98, Tint = (0.8, 0.85, 0.95),
            Health = 28, Speed = 3.0, Damage = 7, Radius = 0.48, Xp = 6, Gold = 2, Resists = Kerchief, Behavior = Behavior.Ranged,
            Ranged = new() { Range = 10, Cooldown = 3.6, Speed = 12, School = School.Physical, Count = 3, Spread = 0.22, Art = "bolt_bone" }, Loot = "kerchief",
            Note = "Ashford's levy kept its crossbows when it lost everything else. Three bolts in a fan, and gaps between them wide enough to stand in." },
        new() { Id = "levy_pike", Name = "Levy Pikeman", Family = Family.Kerchief, Faction = Faction.Kerchief, Visual = "kerchief_rogue", Scale = 1.08, Tint = (1.1, 0.95, 0.72),
            Health = 40, Speed = 3.8, Damage = 11, Radius = 0.5, Xp = 6, Gold = 2, Resists = Kerchief, Behavior = Behavior.Chase,
            Lunge = new(8, 5.5, 0.75, 0.4, 16), Loot = "kerchief",
            Note = "The levy charged with pikes once, at Ashford, and lost. It has been practising since." },
        new() { Id = "kerchief_drummer", Name = "Levy Drummer", Family = Family.Kerchief, Faction = Faction.Kerchief, Visual = "kerchief_hooded", Scale = 1.12, Tint = (1.2, 0.72, 0.7),
            Health = 45, Speed = 2.6, Damage = 6, Radius = 0.5, Xp = 9, Gold = 3, Resists = Kerchief, Behavior = Behavior.Ranged,
            Aura = new(8, 9, 4, Haste: 1.2, Word: "Drum"), Loot = "kerchief",
            Note = "The levy marched to a drum. They still do, to rob a wagon, and they come quicker for it. The drumming stops when it dies." },
        new() { Id = "mb_firepot_nan", Name = "Firepot Nan", Family = Family.Kerchief, Faction = Faction.Kerchief, Visual = "kerchief_hooded", Scale = 1.5, Tint = (1.1, 0.85, 0.75),
            Health = 400, Speed = 3.2, Damage = 10, Radius = 0.75, Mass = 4, Xp = 40, Gold = 15, Resists = Kerchief, Behavior = Behavior.Ranged,
            Ranged = new() { Range = 10, Cooldown = 3.2, Speed = 8.5, School = School.Fire, Lob = true, Count = 3, Spread = 0.45, Zone = new(1.7, 3.5, 0.3), Art = "firepot" },
            Elite = true, Miniboss = true, Loot = "miniboss",
            Lesson = "Three pots at once, and the throwers follow her. Close on her through the gaps.",
            Note = "She cooked for forty-one mouths on the road, and she throws the way she cooks: three pots at a time and none of them cold." },
        new() { Id = "mb_pike_captain", Name = "The Pike-Captain", Family = Family.Kerchief, Faction = Faction.Kerchief, Visual = "kerchief_rogue", Scale = 1.55, Tint = (1.15, 0.92, 0.7),
            Health = 520, Speed = 4.0, Damage = 15, Radius = 0.8, Mass = 6, Xp = 40, Gold = 15, Resists = Kerchief, Behavior = Behavior.Chase,
            Lunge = new(9, 5, 0.8, 0.45, 17), Chain = 1, Summon = new(14, 4, "levy_pike", 1.2, SpawnStyle.Walk, 11, AtTarget: true, Word: "Pikes!"),
            Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.0,
            Lesson = "It runs at you twice, and calls pikes in from the dark to do the same.",
            Note = "Led the levy's charge at Ashford and came back from it. Nobody else did, and it has not let them forget it." },
        new() { Id = "mb_barn_door", Name = "Barn-Door", Family = Family.Kerchief, Faction = Faction.Kerchief, Visual = "kerchief_brute", Scale = 1.7, Tint = (1.05, 0.9, 0.85),
            Health = 760, Speed = 2.8, Damage = 18, Radius = 1.0, Mass = 10, Xp = 40, Gold = 15, Resists = Kerchief, Behavior = Behavior.Guard,
            Guard = new(1.8, 0.8), Slam = new(4.5, 6, 1.1, 2.4, 1.6, Word: "Down!"), Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.3,
            Lesson = "Nothing goes through that door from the front. Go round it, and off the ground it brings down.",
            Note = "Carries an actual barn door, and has done since the wagon it came off. It brings it down on whatever stands still." },
        new() { Id = "mb_levy_sergeant", Name = "The Levy Sergeant", Family = Family.Kerchief, Faction = Faction.Kerchief, Visual = "kerchief_hooded", Scale = 1.55, Tint = (0.85, 0.85, 1.0),
            Health = 480, Speed = 3.0, Damage = 10, Radius = 0.78, Mass = 5, Xp = 40, Gold = 15, Resists = Kerchief, Behavior = Behavior.Ranged,
            Ranged = new() { Range = 11, Cooldown = 2.8, Speed = 13, School = School.Physical, Count = 5, Spread = 0.18, Art = "bolt_bone" },
            Summon = new(15, 3, "levy_crossbow", 1.2, SpawnStyle.Walk, 12, AtTarget: true, Max: 9, Word: "Loose!"), Elite = true, Miniboss = true, Loot = "miniboss",
            Lesson = "Volleys of five, and a file of crossbows behind. Stand in the gaps, or close.",
            Note = "Still drills the levy's crossbows by the old count, and still calls the loose. The bolts have only got better." },
        new() { Id = "mb_drum_major", Name = "The Drum-Major", Family = Family.Kerchief, Faction = Faction.Kerchief, Visual = "kerchief_enforcer", Scale = 1.45, Tint = (1.25, 0.7, 0.7), Glow = 0.08,
            Health = 600, Speed = 3.2, Damage = 15, Radius = 0.85, Mass = 6, Xp = 40, Gold = 15, Resists = Kerchief, Behavior = Behavior.Ranged,
            Aura = new(6, 12, 4.5, Haste: 1.3, Word: "Drum"), Summon = new(12, 6, "footpad", 1.2, SpawnStyle.Walk, 13, AtTarget: true, Max: 30, Word: "To me!"),
            Elite = true, Miniboss = true, Loot = "miniboss", AttackEvery = 1.0,
            Lesson = "It beats the levy in from every side and quickens them. Find the drum.",
            Note = "The levy's drum-major, red to the elbows. Where the drum goes the Kerchiefs go, quicker than you would think." },

        /* ------------------------------------- what rules a people, at the half hour -- */'''),
]
